config/routes.rb
Rails.application.routes.draw do
  root to: 'parkings#index'

  get 'embed' => 'parkings#embed'
  get 'faq'   => 'parkings#faq'
  get 'ideal' => 'parkings#ideal'

  resources :parkings, only: [:index, :show]
end

app/models/parking.rb
class Parking
  include Mongoid::Document
  include Mongoid::Timestamps
  include Geocoder::Model::Mongoid
  include Mongoid::Slug

  ## Relationships
  has_many :availabilities

  ## Schema
  field :name,          type: String
  field :internal_name, type: String
  field :external_id,   type: Integer
  field :lat,           type: Float
  field :lng,           type: Float
  field :address,       type: String
  field :last_refresh_at, type: DateTime
  reverse_geocoded_by :coordinates

  slug :base_name

  ## Indexes
  index internal_name: 1
  index external_id: 1

  ## Scopes
  default_scope -> { asc(:internal_name) }

  ## Callbacks
  before_save :set_internal_name

  ## Methods
  delegate :total, :available, :is_closed?, :is_full?, :fullish?,
    to: :last_availability, allow_nil: true

  def forecast_limit
    ENV['FORECAST_LIMIT'].present? ? ENV['FORECAST_LIMIT'].to_i : 10
  end

  def last_availability
    @last_availability ||= availabilities.last
  end

  def previous_availability
    @previous_availability ||= availabilities.where(:created_at.gte => 30.minutes.ago, :created_at.lte => 25.minutes.ago).first
    @previous_availability ||= availabilities.where(:created_at.lte => 30.minutes.ago).first
  end

  def coordinates
    [lng, lat]
  end

  def trend
    @trend ||= Trend.new(self)
  end

  def trend_and_previous_available
    previous = trend.unknown? && "N/A" || previous_availability.available

    [trend, previous]
  end

  def pr?
    name =~ /P\+R/
  end

  def base_name
    pr? && name[4..-1] || name
  end

  def sort_criteria
    is_full? && 1 || is_closed? && 2 || 0
  end

  # Returns an array of forecasted availabilities
  def forecast(delay)
    time = delay.minutes.since
    steps = (0..forecast_limit).to_a.map { |num| time - num.weeks}
    ary = steps.map { |time| self.availabilities.around(time) }.flatten
    ary.reject! &:is_closed?
    ary.sort_by! &:available

    # Removes the lower 10% and the upper 10% in case there is some exterme values
    to_trim = ary.size / 20
    to_trim.times { ary.shift; ary.pop; }

    if block_given?
      yield ary.first.try(:available), ary.last.try(:available)
    else
      [ary.first.try(:available), ary.last.try(:available)]
    end
  end

  def method_missing(name, *args, &block)
    if name.to_s.starts_with?('fullish_')
      delay = name.to_s.split('_').last.to_i

      if (lowest = forecast(delay).first)
        lowest < (total / (10.0))
      else
        true
      end
    else
      super
    end
  end

  private

  def set_internal_name
    self.internal_name = name =~ /P\+R/ ? (name.gsub("P+R ", "")+" (P+R)") : name
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :load_resource, only: :show
  before_action :load_resources, only: [:index, :embed]

  respond_to :html, :json

  def index
    respond_with @parkings
  end

  def show
  end

  def ideal
    # Sort by distance
    if params[:lat] && params[:lng]
      @parkings.sort_by! { |p| p.distance_from params.values_at(:lat, :lng)}

      method = 'fullish'
      method += "_#{params[:delay].to_i.to_s}" if params[:delay]
      method += '?'

      @parking = @parkings.reject { |parking| parking.send(method) }.first
      @parkings.delete @parking
    end

    show
  end

  def embed
    render action: :index
  end

  def faq; end

  private

  def load_resource
    @parking = Parking.find params[:id]
  end

  def load_resources
    @parkings = Parking.all.to_a
  end
end

app/views/parkings/_forecast.html.haml
- cache(parking_forecast_cache_key(parking, delay)) do
  %h4
    = t 'forecast.labels.main'
    = t "forecast.labels.#{delay}"
  .forecast-content.mb-2
    - parking.forecast(delay) do |min, max|
      - if min.nil? && max.nil?
        = t 'forecast.closed'
      - else
        - if parking.send("fullish_#{delay}?")
          = t 'forecast.fullish', max: max
        - else
          = t 'forecast.free.should'
          %span.main-free= min
          = t 'forecast.free.and'
          %span.main-free= max
          = t 'forecast.free.places'

app/views/parkings/_main_parking.html.haml
- parking = @parking
- content_for(:meta) do
  %meta{property: 'og:title', content: "Les parkings à Strasbourg - #{parking.internal_name}"}
  %meta{property: 'og:url', content: parking_url(parking)}
.main-parking-outer
  %h2.parking-title= parking.internal_name
  .main-parking
    .main-parking-availabilities
      %h4= t 'main.titles.current'
      .availability-content
        - if parking.is_closed?
          = t 'main.labels.closed'
          %span.main-free
            = t 'main.labels.closed_item'
        - else
          #{parking.total} #{t('place').pluralize}, #{t('including')}
          %span.main-free
            = parking.available
          #{free_label}.
      - [20, 40, 60].each do |delay|
        = render partial: 'forecast', locals: {parking: parking, delay: delay}
      .forecast-disclosure
        = t('predictions_disclosure')

    %h4
      = t 'main.titles.location'
      %span.map-link.pull-right
    .main-parking-map

      #parking-map{data: {lng: parking.lng.to_s, lat: parking.lat.to_s, name: parking.base_name}}

app/views/parkings/_parking.html.haml
- cache parking do
  .col-12.col-sm-4{data: {lat: parking.lat, lng: parking.lng, index: parking_counter}}
    = link_to parking, class: parking_class(parking).push(:card, :parking, :'mt-4') do
      .card-body.row{style: "margin-top:0 !important;"}
        .col-12.col-sm-6
          %h3.h5.parking-name{data: {clean: parking.internal_name}, class: parking_class(parking)}
            = parking.base_name
            - if parking.pr?
              %sup.pr-label
                &nbsp;P+R&nbsp;
          .parking-distance
        %div{class: parking.is_closed? ? "col-12 col-sm-6" : "col-12 col-sm-4"}
          .parking-data{class: parking_class(parking)}
            - if parking.is_closed?
              %span.available= t('closed')
              %br
            - else
              %span.available= parking.available
              %span.free= free_label(parking)
              %br
            %span.total
              = "#{parking.total}"
              %span.total-label
                = t('place').pluralize
        - unless parking.is_closed?
          .col-12.col-sm-2
            .parking-trend
              = trend_node(parking)

app/views/parkings/faq.html.haml
- cache(faq_meta_cache_key) do
  - content_for(:meta) do
    %meta{property: 'og:title', content: 'Les parkings à Strasbourg - FAQ'}
    %meta{property: 'og:url', content: faq_url}

- cache(faq_cache_key) do
  .row
    .col-12
      - unless embedded?
        = link_to root_path, class: 'home-link' do
          %h1.app-title= t 'app.title'
      .info-page
        %p= t('footer_text').html_safe
        %p= t('footer_addenum').html_safe
        %p= t('predictions_disclosure')
        %span.embed-instructions
          %p= t('footer_embed')
          %pre
            %code{style: 'width:100%;'}
              :escaped
                <iframe src="https://www.parking-strasbourg.eu/embed" width="100%" height="1200px"></iframe>

app/views/parkings/index.html.haml
- cache(parkings_index_cache_key) do
  - if false
    .row
      .col-12
        .app-subtitle
          %span.ideal
            %span.disabled
              = t 'ideal.disabled.park'
              = link_to t('ideal.disabled.now'), ideal_path
              = t 'ideal.disabled.or'
              = link_to t('ideal.disabled.20'), ideal_path(delay: 20)
              %span.sep -
              = link_to t('ideal.disabled.40'), ideal_path(delay: 40)
              %span.sep -
              = link_to t('ideal.disabled.60'), ideal_path(delay: 60)

            %span.enabled-geoloc.hidden= t 'ideal.enabled-geoloc'
            %span.enabled-address.hidden= t 'ideal.enabled-address'

  .row.mt-2
    .col-12.text-right
      %small.text-muted.infos
        = last_refresh(@parkings)
        = link_to t('info'), faq_path, class: "hidden-phone"
    .col-12.text-center.mt-4
      .row
        .col-12.col-sm-8.offset-sm-2
          .input-group.text-center
            .input-group-addon.btn#location-filter
              %i.fa.fa-map-marker
              %i.fa.fa-times.hidden
              %i.fa.fa-spinner.fa-spin.hidden
            %input.form-control#address-filter{type: "text", placeholder: t('filters.address.placeholder')}

  .row.parkings.mt-2
    = render @parkings

app/views/parkings/info.html.haml
- content_for(:meta) do
  %meta{property: 'og:title', content: 'Les parkings à Strasbourg - informations'}
  %meta{property: 'og:url', content: info_url}
- unless embedded?
  = link_to root_path, class: 'home-link' do
    %h1.app-title= t 'app.title'
.info-page
  %p= t('footer_text').html_safe
  %p= t('footer_addenum').html_safe
  %p= t('predictions_disclosure')
  %span.embed-instructions
    %p= t('footer_embed')
    %textarea{style: 'width: 100%;', rows: 1}
      :escaped
        <iframe src="http://www.parking-strasbourg.eu/embed" width="100%" height="1200px"></iframe>

app/views/parkings/show.html.haml
- parking = @parking
- cache do
  - content_for(:meta) do
    %meta{property: 'og:title', content: "Les parkings à Strasbourg - #{parking.internal_name}"}
    %meta{property: 'og:url', content: parking_url(parking)}

- cache parking do
  .row.main-parking
    .col-12
      = link_to "/", class: "text-muted h4 mt-0 mb-4 d-block" do
        ← retour à l'accueil
    .col-12.col-sm-6
      .main-parking-availabilities
        %h4= t 'main.titles.current'
        .availability-content.mb-2
          - if parking.is_closed?
            = t 'main.labels.closed'
            %span.main-free
              = t 'main.labels.closed_item'
          - else
            #{parking.total} #{t('place').pluralize}, #{t('including')}
            %span.main-free
              = parking.available
            #{free_label}.
        - [20, 40, 60].each do |delay|
          = render partial: 'forecast', locals: {parking: parking, delay: delay}
        .forecast-disclosure
          = t('predictions_disclosure')
    .col-12.col-sm-6
      %h4
        = t 'main.titles.location'
        %span.map-link.pull-right
      .main-parking-map
        #parking-map{data: {lng: parking.lng.to_s, lat: parking.lat.to_s, name: parking.base_name}}